spring.application.name=pantry-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/pantry_db
spring.datasource.username=postgres
spring.datasource.password=k@mil

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
